name = "street-fighter-server"
main = "src/index.js"
compatibility_date = "2025-05-09"
usage_model = "bundled"

[assets]
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "STREET_FIGHTER"
id = "9d1cf83b326b4b4f98732e3aa8f6a0b8"
preview_id = "c17d51ade21b4184ad3ad22fbd74c70b"

[[durable_objects.bindings]]
name = "STREET_FIGHTER_ROOM"
class_name = "StreetFighterRoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["StreetFighterRoomDO"] 